version: '3'
services:
  sqlite3_db:
    image: nouchka/sqlite3:latest
    volumes:
      - twitch-data:/home/app/db

  streamer_api:
    image: my-api:1.0
    depends_on:
      - sqlite3_db
    restart: always
    ports:
      - 6000:6000
    links:
      - sqlite3_db
volumes:
  twitch-data:
    driver: local
    
